# Stage 1: build
FROM node:alpine3.23 as builder
WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Stage 2: start webserver
FROM nginx:stable-alpine3.23-perl
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]